In [2]:
import pandas as pd

In [1]:
import numpy as np

In [17]:
df = pd.read_csv("dataset_CB23.csv")

In [18]:
df

,patient_id,sex,age_years,years_education,visit,APOE4,apoe_result,family_dementia_history,ptau_result,ttau_result,...,Depression,cdr_global,DX,cdr_sob,LHVL,LHVR,LHV,LWMV,VASCULAR,DXCHANGE
0,1,f,51,11,V1,0.0,e3/e3,Yes,16.3,331.0,...,0.0,2.0,Dem,16.5,-1.701,-0.521,-2.221,-0.723,0.0,Stable: Dementia
1,2,m,76,10,V1,2.0,e4/e4,Yes,22.9,223.0,...,1.0,0.5,MCI,1.5,0.254,0.025,0.279,0.000,1.0,Reversion: MCI to NC
2,3,f,61,14,V1,0.0,e3/e3,Yes,19.8,202.0,...,NaN,1.0,Dem,5.5,-0.642,-0.657,-1.299,0.210,1.0,Stable: Dementia
3,4,f,53,10,V1,1.0,e2/e4,Yes,22.1,80.0,...,1.0,NaN,NaN,NaN,-2.135,0.950,-1.185,1.042,1.0,NaN
4,5,f,77,20,V1,1.0,e3/e4,Yes,NaN,NaN,...,1.0,2.0,Dem,5.5,0.095,-1.189,-1.094,-0.567,0.0,Stable: Dementia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,996,m,93,12,V3,NaN,NaN,Yes,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,997,m,86,13,V3,1.0,e3/e4,Yes,NaN,NaN,...,1.0,0.5,MCI,3.5,NaN,NaN,NaN,NaN,NaN,NaN
2997,998,m,66,20,V3,1.0,e3/e4,Yes,NaN,NaN,...,1.0,3.0,Dem,8.5,NaN,NaN,NaN,NaN,NaN,NaN
2998,999,m,76,16,V3,1.0,e3/e4,Yes,NaN,NaN,...,1.0,0.0,NC,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2999,1000,un,63,14,V3,2.0,e4/e4,No,NaN,NaN,...,1.0,0.0,NC,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# df.set_index('patient_id', inplace=True)

In [16]:
df

,sex,age_years,years_education,visit,APOE4,apoe_result,family_dementia_history,ptau_result,ttau_result,abeta42_result,...,Depression,cdr_global,DX,cdr_sob,LHVL,LHVR,LHV,LWMV,VASCULAR,DXCHANGE
patient_id,,,,,,,,,,,,,,,,,,,,,
1,f,51,11,V1,0.0,e3/e3,Yes,16.3,331.0,1363.0,...,0.0,2.0,Dem,16.5,-1.701,-0.521,-2.221,-0.723,0.0,Stable: Dementia
2,m,76,10,V1,2.0,e4/e4,Yes,22.9,223.0,1700.0,...,1.0,0.5,MCI,1.5,0.254,0.025,0.279,0.000,1.0,Reversion: MCI to NC
3,f,61,14,V1,0.0,e3/e3,Yes,19.8,202.0,1406.0,...,NaN,1.0,Dem,5.5,-0.642,-0.657,-1.299,0.210,1.0,Stable: Dementia
4,f,53,10,V1,1.0,e2/e4,Yes,22.1,80.0,1150.0,...,1.0,NaN,NaN,NaN,-2.135,0.950,-1.185,1.042,1.0,NaN
5,f,77,20,V1,1.0,e3/e4,Yes,NaN,NaN,NaN,...,1.0,2.0,Dem,5.5,0.095,-1.189,-1.094,-0.567,0.0,Stable: Dementia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,m,93,12,V3,NaN,NaN,Yes,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,m,86,13,V3,1.0,e3/e4,Yes,NaN,NaN,NaN,...,1.0,0.5,MCI,3.5,NaN,NaN,NaN,NaN,NaN,NaN
998,m,66,20,V3,1.0,e3/e4,Yes,NaN,NaN,NaN,...,1.0,3.0,Dem,8.5,NaN,NaN,NaN,NaN,NaN,NaN
999,m,76,16,V3,1.0,e3/e4,Yes,NaN,NaN,NaN,...,1.0,0.0,NC,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1000,un,63,14,V3,2.0,e4/e4,No,NaN,NaN,NaN,...,1.0,0.0,NC,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(3000, 29)

In [7]:
df.columns

Index(['patient_id', 'sex', 'age_years', 'years_education', 'visit', 'APOE4',
       'apoe_result', 'family_dementia_history', 'ptau_result', 'ttau_result',
       'abeta42_result', 'AMYL', 'TAUO', 'NEUROD', 'ATN', 'MONTHS',
       'mmse_total', 'np_date', 'gds_total', 'Depression', 'cdr_global', 'DX',
       'cdr_sob', 'LHVL', 'LHVR', 'LHV', 'LWMV', 'VASCULAR', 'DXCHANGE'],
      dtype='object')

In [8]:
df.dtypes

patient_id                   int64
sex                         object
age_years                    int64
years_education              int64
visit                       object
APOE4                      float64
apoe_result                 object
family_dementia_history     object
ptau_result                float64
ttau_result                float64
abeta42_result             float64
AMYL                       float64
TAUO                       float64
NEUROD                     float64
ATN                         object
MONTHS                     float64
mmse_total                 float64
np_date                     object
gds_total                  float64
Depression                 float64
cdr_global                 float64
DX                          object
cdr_sob                    float64
LHVL                       float64
LHVR                       float64
LHV                        float64
LWMV                       float64
VASCULAR                   float64
DXCHANGE                    object
dtype: object

In [9]:
# per column missing values
df.isnull().sum()

patient_id                    0
sex                           0
age_years                     0
years_education               0
visit                         0
APOE4                       309
apoe_result                 309
family_dementia_history       0
ptau_result                2100
ttau_result                2100
abeta42_result             2100
AMYL                       2100
TAUO                       2100
NEUROD                     2100
ATN                        2100
MONTHS                      461
mmse_total                  287
np_date                     287
gds_total                   268
Depression                  268
cdr_global                  289
DX                          289
cdr_sob                     289
LHVL                       2000
LHVR                       2000
LHV                        2000
LWMV                       2000
VASCULAR                   2000
DXCHANGE                   2190
dtype: int64

In [14]:
df["ttau_result"]

0       331.0
1       223.0
2       202.0
3        80.0
4         NaN
        ...
2995      NaN
2996      NaN
2997      NaN
2998      NaN
2999      NaN
Name: ttau_result, Length: 3000, dtype: float64